export { default as StartScreen } from './StartScreen'
export { default as LoginScreen } from './LoginScreen'
export { default as RegisterScreen } from './RegisterScreen'
export { default as ResetPasswordScreen } from './ResetPasswordScreen'
export { default as Dashboard } from './Dashboard'
export { default as Menulist } from './Menulist'
export { default as Orderlist } from './Orderlist'
export { default as Orderslist } from './Orderslist'
export { default as Weather } from './Weather'
export { default as StoreOrdersDetail} from './StoreOrdersDetail'

